/** Moroccan cities (French names) offered when configuring delivery zones. */
export const MOROCCAN_CITIES = [
  "Casablanca",
  "Rabat",
  "Fès",
  "Marrakech",
  "Tanger",
  "Agadir",
  "Meknès",
  "Oujda",
  "Tétouan",
  "Kénitra",
  "Safi",
  "El Jadida",
  "Béni Mellal",
  "Khouribga",
  "Settat",
  "Nador",
  "Taza",
  "Ouarzazate",
  "Errachidia",
  "Laâyoune",
  "Dakhla",
  "Guelmim",
  "Taroudant",
  "Essaouira",
  "Salé",
  "Mohammédia",
  "Berrechid",
  "Taourirt",
  "Guercif",
  "Chefchaouen",
  "Al Hoceïma",
  "Sidi Kacem",
  "Sidi Slimane",
  "Khénifra",
  "Zagora",
  "Tinghir",
  "Azilal",
] as const;
